name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josefusan
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/New_York
          
          # Languages Plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Isocalendar Plugin - 3D contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Stars Plugin - Recently starred repos
          plugin_stars: yes
          plugin_stars_limit: 3
          
          # Lines of code
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # Follow-up of issues/PRs
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_followup_indepth: yes
